[tool.poetry]
name = "sabogaapi"
version = "0.0.11"
description = ""
authors = ["Tjark Sievers <tjarksievers@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.0"
fastapi = "^0.110.1"
uvicorn = "^0.23.2"
python-dotenv = "^1.0.0"
fastapi-users = {extras = ["beanie"], version = "^13.0.0"}
beanie = "^1.26.0"
casbin = "^1.36.0"
fastapi-authz = "^1.0.0"

[tool.poetry.group.dev.dependencies]
scriv = "^1.5.0"
pre-commit = "^3.5.0"
tox = "^4.11.3"
httpx = "^0.25.2"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
