[tool.poetry]
name = "sabogaapi"
version = "0.0.26"
description = ""
authors = ["Tjark Sievers <tjarksievers@icloud.com>"]
readme = "README.md"

[tool.poetry.scripts]
scrape = "sabogaapi.api_v1.scraper:scrape"


[tool.poetry.dependencies]
python = "^3.12.0"
fastapi = "^0.110.1"
uvicorn = "^0.23.2"
python-dotenv = "^1.0.0"
beanie = "^1.26.0"
casbin = "^1.36.0"
python-multipart = "^0.0.9"
requests = "^2.32.3"

[tool.poetry.group.dev.dependencies]
scriv = "^1.5.0"
pre-commit = "^3.5.0"
tox = "^4.11.3"
httpx = "^0.25.2"
pytest = "^7.4.3"
ruff = "^0.5.6"
mongomock-motor = "^0.0.31"
setuptools = "^72.1.0"
pytest-cov = "^5.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
