[tool.poetry]
name = "sabogaapi"
version = "0.0.2"
description = ""
authors = ["Tjark Sievers <tjarksievers@icloud.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12.0"
fastapi = "^0.104.1"
uvicorn = "^0.23.2"
sqlmodel = "^0.0.11"
alembic = "^1.12.1"
python-dotenv = "^1.0.0"
pymysql = "^1.1.0"

[tool.poetry.group.dev.dependencies]
scriv = "^1.5.0"
pre-commit = "^3.5.0"
tox = "^4.11.3"
httpx = "^0.25.2"
pytest = "^7.4.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
