version: '3.8'

services:
  api:
    build:
      context: ../
      dockerfile: api-testing/Dockerfile
    image: saboga-api:latest
    container_name: saboga-api
    ports:
      - "8000:8000"
    volumes:
      - ../migrations:/app/migrations
    env_file:
      - ../.env
    networks:
      - saboga-api

  database:
    image: mariadb:latest
    container_name: saboga-database
    ports:
      - "3306:3306"
    env_file:
      - ../.env
    networks:
      - saboga-api

networks:
  saboga-api:
    name: saboga-api
    driver: bridge
