services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v3.0
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--providers.docker.network=api-testing_reverse-proxy"
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - reverse-proxy

  saboga-api:
    build:
      context: ../
      dockerfile: api-testing/Dockerfile
    image: saboga-api:latest
    container_name: saboga-api
    labels:
      - "traefik.http.routers.saboga-api.rule=Host(`api.saboga.docker.localhost`)"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - reverse-proxy
    networks:
      - reverse-proxy
      - saboga-api


  saboga-database:
    image: mongo:jammy
    container_name: saboga-database
    env_file:
      - .env
    volumes:
      - ./init_db.sh:/docker-entrypoint-initdb.d/init_db.sh
      - ./dump:/dump
    networks:
      - saboga-api

networks:
  saboga-api:
    driver: bridge
    internal: true
  reverse-proxy:
    driver: bridge
