services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    expose:
      - "9090"
    labels:
      - "traefik.http.routers.prometheus.rule=Host(`prometheus.localhost`)"
      - "traefik.http.routers.prometheus.tls=true"
      - "traefik.docker.network=saboga-reverse-proxy"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - saboga-reverse-proxy
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    container_name: grafana
    expose:
      - "3000"
    labels:
      - "traefik.http.routers.grafana.rule=Host(`grafana.localhost`)"
      - "traefik.http.routers.grafana.tls=true"
      - "traefik.docker.network=saboga-reverse-proxy"
    networks:
      - saboga-reverse-proxy
      - loki
    volumes:
      - ./grafana_data:/var/lib/grafana

  loki:
    image: grafana/loki:latest
    container_name: loki
    expose:
      - "3100"
    networks:
      - loki

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - /var/log:/var/log:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
    command: -config.file=/etc/promtail/promtail-config.yaml
    networks:
      - loki

  saboga-api:
    networks:
      - loki

networks:
  loki:
    driver: bridge
    internal: true
