name: saboga

services:
  reverse-proxy:
    container_name: traefik
    image: traefik:v3
    command:
      - "--api.dashboard=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
      - "--providers.docker.network=saboga-reverse-proxy"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.file.directory=/etc/traefik/dynamic"
    labels:
      - "traefik.http.routers.dashboard.rule=Host(`traefik.localhost`)"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls=true"
      - "traefik.http.routers.whoami.entrypoints=websecure"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik-certs.yaml:/etc/traefik/dynamic/certs-traefik.yaml
      - ./certs/:/etc/certs/
    networks:
      - saboga-reverse-proxy

  saboga-api:
    image: saboga-api:latest
    build:
      context: ../
      dockerfile: api-testing/Dockerfile
    container_name: saboga-api
    labels:
      - "traefik.http.routers.saboga-api.rule=Host(`saboga.localhost`) && PathPrefix(`/api`)"
      - "traefik.http.middlewares.saboga-api-stripprefix.stripprefix.prefixes=/api"
      - "traefik.http.routers.saboga-api.middlewares=saboga-api-stripprefix"
      - "traefik.http.routers.saboga-api.tls=true"
      - "traefik.docker.network=saboga-reverse-proxy"
      - "traefik.http.services.saboga-api.loadbalancer.server.port=8000"
    expose:
      - "8000"
    env_file:
      - .env
    depends_on:
      - reverse-proxy
    networks:
      - saboga-reverse-proxy
      - saboga-api
    volumes:
      - staticfiles:/app/static
      - img:/app/img
    develop:
      watch:
        - action: sync
          path: ../
          target: /app
          ignore:
            - ../.venv/
        - action: rebuild
          path: ../pyproject.toml

  saboga-manage:
    image: saboga-api:latest
    build:
      context: ../
      dockerfile: api-testing/Dockerfile
    container_name: saboga-manage
    env_file:
      - .env
    networks:
      - saboga-api

  saboga-database:
    image: postgres:17
    container_name: saboga-database
    env_file:
      - .env
    volumes:
      - saboga_db_data:/var/lib/postgresql/data
    networks:
      - saboga-api

  # static file server using nginx
  static-server:
    image: nginx:alpine
    container_name: saboga-static
    labels:
      - "traefik.http.routers.saboga-static.rule=Host(`saboga.localhost`) && PathPrefix(`/api/static`)"
      - "traefik.http.routers.saboga-static.tls=true"
      - "traefik.http.routers.saboga-img.rule=Host(`saboga.localhost`) && PathPrefix(`/api/img`)"
      - "traefik.http.routers.saboga-img.tls=true"
      - "traefik.docker.network=saboga-reverse-proxy"
    volumes:
      - staticfiles:/usr/share/nginx/html/static:ro
      - img:/usr/share/nginx/html/img:ro
      - ./nginx-static.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - saboga-reverse-proxy

volumes:
  saboga_db_data:
  staticfiles:
  img:

networks:
  saboga-api:
    driver: bridge
    internal: true
    name: saboga-api
  saboga-reverse-proxy:
    driver: bridge
    name: saboga-reverse-proxy
