# Generated by Django 6.0 on 2025-12-26 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BoardgameNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
            ],
            options={
                "db_table": "boardgame_network",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bgg_id", models.IntegerField(db_index=True, unique=True)),
                ("type", models.CharField(default="category", max_length=50)),
            ],
            options={
                "db_table": "categories",
            },
        ),
        migrations.CreateModel(
            name="CategoryNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
            ],
            options={
                "db_table": "category_network",
            },
        ),
        migrations.CreateModel(
            name="Designer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bgg_id", models.IntegerField(db_index=True, unique=True)),
                ("type", models.CharField(default="designer", max_length=50)),
            ],
            options={
                "db_table": "designers",
            },
        ),
        migrations.CreateModel(
            name="DesignerNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
            ],
            options={
                "db_table": "designer_network",
            },
        ),
        migrations.CreateModel(
            name="Family",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bgg_id", models.IntegerField(db_index=True, unique=True)),
                ("type", models.CharField(default="family", max_length=50)),
            ],
            options={
                "db_table": "families",
            },
        ),
        migrations.CreateModel(
            name="FamilyNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
            ],
            options={
                "db_table": "family_network",
            },
        ),
        migrations.CreateModel(
            name="HeterogeneousGraphData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
                ("meta", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "heterogeneous_graph",
            },
        ),
        migrations.CreateModel(
            name="Mechanic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("bgg_id", models.IntegerField(db_index=True, unique=True)),
                ("type", models.CharField(default="mechanic", max_length=50)),
            ],
            options={
                "db_table": "mechanics",
            },
        ),
        migrations.CreateModel(
            name="MechanicNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
            ],
            options={
                "db_table": "mechanic_network",
            },
        ),
        migrations.CreateModel(
            name="ProjectedGraphData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("graph_type", models.CharField(db_index=True, max_length=255)),
                ("created_at", models.DateTimeField(db_index=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("nodes", models.JSONField()),
                ("edges", models.JSONField()),
                ("meta", models.JSONField(default=dict)),
            ],
            options={
                "db_table": "projected_graphs",
            },
        ),
        migrations.CreateModel(
            name="Boardgame",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bgg_id", models.IntegerField(db_index=True, unique=True)),
                ("bgg_rank", models.IntegerField(db_index=True, null=True)),
                ("name", models.CharField(default="", max_length=1024)),
                ("bgg_geek_rating", models.FloatField(blank=True, null=True)),
                ("bgg_average_rating", models.FloatField(blank=True, null=True)),
                ("bgg_rank_volatility", models.FloatField(blank=True, null=True)),
                ("bgg_rank_trend", models.FloatField(blank=True, null=True)),
                (
                    "bgg_geek_rating_volatility",
                    models.FloatField(blank=True, null=True),
                ),
                ("bgg_geek_rating_trend", models.FloatField(blank=True, null=True)),
                (
                    "bgg_average_rating_volatility",
                    models.FloatField(blank=True, null=True),
                ),
                ("bgg_average_rating_trend", models.FloatField(blank=True, null=True)),
                ("mean_trend", models.FloatField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, null=True)),
                ("thumbnail_url", models.URLField(blank=True, null=True)),
                ("year_published", models.IntegerField(blank=True, null=True)),
                ("minplayers", models.IntegerField(blank=True, null=True)),
                ("maxplayers", models.IntegerField(blank=True, null=True)),
                ("playingtime", models.IntegerField(blank=True, null=True)),
                ("minplaytime", models.IntegerField(blank=True, null=True)),
                ("maxplaytime", models.IntegerField(blank=True, null=True)),
                ("type", models.CharField(default="boardgame", max_length=50)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="boardgames", to="api.category"
                    ),
                ),
                (
                    "designers",
                    models.ManyToManyField(
                        blank=True, related_name="boardgames", to="api.designer"
                    ),
                ),
                (
                    "families",
                    models.ManyToManyField(
                        blank=True, related_name="boardgames", to="api.family"
                    ),
                ),
                (
                    "mechanics",
                    models.ManyToManyField(
                        blank=True, related_name="boardgames", to="api.mechanic"
                    ),
                ),
            ],
            options={
                "db_table": "boardgames",
            },
        ),
        migrations.CreateModel(
            name="RankHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(db_index=True)),
                ("bgg_rank", models.IntegerField(blank=True, null=True)),
                ("bgg_geek_rating", models.FloatField(blank=True, null=True)),
                ("bgg_average_rating", models.FloatField(blank=True, null=True)),
                (
                    "boardgame",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bgg_rank_history",
                        to="api.boardgame",
                    ),
                ),
            ],
            options={
                "db_table": "rank_history",
                "indexes": [
                    models.Index(
                        fields=["boardgame", "date"],
                        name="ix_rankhistory_boardgame_date",
                    )
                ],
            },
        ),
    ]
