# Generated by Django 5.2.12 on 2026-03-13 05:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_boardgame_created_at_boardgame_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="rankhistory",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
