# Generated by Django 5.2.12 on 2026-03-13 17:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_rankhistory_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="boardgame",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="image_url",
            field=models.URLField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="boardgame",
            name="thumbnail_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
