# Generated by Django 5.2.12 on 2026-03-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_boardgame_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
