# Generated by Django 5.2.12 on 2026-03-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_boardgame_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
