# Generated by Django 5.2.12 on 2026-03-14 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_boardgame_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='image_url',
        ),
        migrations.RemoveField(
            model_name='boardgame',
            name='thumbnail_url',
        ),
    ]
