version: '3.8'

services:
  api:
    build: ..
    image: saboga-api:latest
    container_name: saboga-api
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    networks:
      - saboga-api

  database:
    image: mariadb:latest
    container_name: database
    ports:
      - "3306:3306"
    volumes: # local file, mariadb automatically creates a db from the sql dump
      - ${PWD}/test-database/boardgame.sql:/docker-entrypoint-initdb.d/boardgame.sql
    env_file:
      - ../.env
    networks:
      - saboga-api

networks:
  saboga-api:
    name: saboga-api
    driver: bridge
