"""change graph structure

Revision ID: 57c69f74db9f
Revises: a2e99a83e957
Create Date: 2025-12-25 07:08:43.541668

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "57c69f74db9f"
down_revision: Union[str, Sequence[str], None] = "a2e99a83e957"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heterogeneous_graph",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("edges", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_heterogeneous_graph_created_at"),
        "heterogeneous_graph",
        ["created_at"],
        unique=False,
    )
    op.create_table(
        "projected_graphs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("graph_type", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("nodes", sa.JSON(), nullable=False),
        sa.Column("edges", sa.JSON(), nullable=False),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_projected_graphs_created_at"),
        "projected_graphs",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_projected_graphs_graph_type"),
        "projected_graphs",
        ["graph_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projected_graphs_graph_type"), table_name="projected_graphs")
    op.drop_index(op.f("ix_projected_graphs_created_at"), table_name="projected_graphs")
    op.drop_table("projected_graphs")
    op.drop_index(
        op.f("ix_heterogeneous_graph_created_at"), table_name="heterogeneous_graph"
    )
    op.drop_table("heterogeneous_graph")
    # ### end Alembic commands ###
