"""initial revision

Revision ID: a2e99a83e957
Revises:
Create Date: 2025-10-15 21:47:57.516013

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a2e99a83e957'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardgame_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('boardgames',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('bgg_rank', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bgg_geek_rating', sa.Float(), nullable=True),
    sa.Column('bgg_average_rating', sa.Float(), nullable=True),
    sa.Column('bgg_rank_volatility', sa.Float(), nullable=True),
    sa.Column('bgg_rank_trend', sa.Float(), nullable=True),
    sa.Column('bgg_geek_rating_volatility', sa.Float(), nullable=True),
    sa.Column('bgg_geek_rating_trend', sa.Float(), nullable=True),
    sa.Column('bgg_average_rating_volatility', sa.Float(), nullable=True),
    sa.Column('bgg_average_rating_trend', sa.Float(), nullable=True),
    sa.Column('mean_trend', sa.Float(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('thumbnail_url', sa.String(), nullable=True),
    sa.Column('year_published', sa.Integer(), nullable=True),
    sa.Column('minplayers', sa.Integer(), nullable=True),
    sa.Column('maxplayers', sa.Integer(), nullable=True),
    sa.Column('playingtime', sa.Integer(), nullable=True),
    sa.Column('minplaytime', sa.Integer(), nullable=True),
    sa.Column('maxplaytime', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boardgames_bgg_id'), 'boardgames', ['bgg_id'], unique=True)
    op.create_index(op.f('ix_boardgames_bgg_rank'), 'boardgames', ['bgg_rank'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_bgg_id'), 'categories', ['bgg_id'], unique=True)
    op.create_table('category_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designer_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('designers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_designers_bgg_id'), 'designers', ['bgg_id'], unique=True)
    op.create_table('families',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_families_bgg_id'), 'families', ['bgg_id'], unique=True)
    op.create_table('family_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanic_network',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nodes', sa.JSON(), nullable=False),
    sa.Column('edges', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mechanics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('bgg_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mechanics_bgg_id'), 'mechanics', ['bgg_id'], unique=True)
    op.create_table('boardgame_category',
    sa.Column('boardgame_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boardgame_id'], ['boardgames.id'], ),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('boardgame_id', 'category_id')
    )
    op.create_table('boardgame_designer',
    sa.Column('boardgame_id', sa.Integer(), nullable=False),
    sa.Column('designer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boardgame_id'], ['boardgames.id'], ),
    sa.ForeignKeyConstraint(['designer_id'], ['designers.id'], ),
    sa.PrimaryKeyConstraint('boardgame_id', 'designer_id')
    )
    op.create_table('boardgame_family',
    sa.Column('boardgame_id', sa.Integer(), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boardgame_id'], ['boardgames.id'], ),
    sa.ForeignKeyConstraint(['family_id'], ['families.id'], ),
    sa.PrimaryKeyConstraint('boardgame_id', 'family_id')
    )
    op.create_table('boardgame_mechanic',
    sa.Column('boardgame_id', sa.Integer(), nullable=False),
    sa.Column('mechanic_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['boardgame_id'], ['boardgames.id'], ),
    sa.ForeignKeyConstraint(['mechanic_id'], ['mechanics.id'], ),
    sa.PrimaryKeyConstraint('boardgame_id', 'mechanic_id')
    )
    op.create_table('rank_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('boardgame_id', sa.Integer(), nullable=False),
    sa.Column('bgg_rank', sa.Integer(), nullable=True),
    sa.Column('bgg_geek_rating', sa.Float(), nullable=True),
    sa.Column('bgg_average_rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['boardgame_id'], ['boardgames.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rank_history_boardgame_id'), 'rank_history', ['boardgame_id'], unique=False)
    op.create_index(op.f('ix_rank_history_date'), 'rank_history', ['date'], unique=False)
    op.create_index('ix_rankhistory_boardgame_date', 'rank_history', ['boardgame_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_rankhistory_boardgame_date', table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_date'), table_name='rank_history')
    op.drop_index(op.f('ix_rank_history_boardgame_id'), table_name='rank_history')
    op.drop_table('rank_history')
    op.drop_table('boardgame_mechanic')
    op.drop_table('boardgame_family')
    op.drop_table('boardgame_designer')
    op.drop_table('boardgame_category')
    op.drop_index(op.f('ix_mechanics_bgg_id'), table_name='mechanics')
    op.drop_table('mechanics')
    op.drop_table('mechanic_network')
    op.drop_table('family_network')
    op.drop_index(op.f('ix_families_bgg_id'), table_name='families')
    op.drop_table('families')
    op.drop_index(op.f('ix_designers_bgg_id'), table_name='designers')
    op.drop_table('designers')
    op.drop_table('designer_network')
    op.drop_table('category_network')
    op.drop_index(op.f('ix_categories_bgg_id'), table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_boardgames_bgg_rank'), table_name='boardgames')
    op.drop_index(op.f('ix_boardgames_bgg_id'), table_name='boardgames')
    op.drop_table('boardgames')
    op.drop_table('boardgame_network')
    # ### end Alembic commands ###
