"""init

Revision ID: 141829b0b858
Revises: 
Create Date: 2023-12-17 21:33:05.226946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '141829b0b858'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boardgame',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bgg_rating', sa.Integer(), nullable=False),
    sa.Column('owner', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('wishlist', sa.Boolean(), nullable=False),
    sa.Column('player_min', sa.Integer(), nullable=False),
    sa.Column('player_recommended_min', sa.Integer(), nullable=False),
    sa.Column('player_max', sa.Integer(), nullable=False),
    sa.Column('player_recommended_max', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('game_id')
    )
    op.create_index(op.f('ix_boardgame_name'), 'boardgame', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_boardgame_name'), table_name='boardgame')
    op.drop_table('boardgame')
    # ### end Alembic commands ###
