"""Init

Revision ID: 65d3149e15e1
Revises:
Create Date: 2024-04-06 13:31:57.902653

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "65d3149e15e1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "boardgame",
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bgg_rating", sa.Float(), nullable=False),
        sa.Column("owner", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("player_min", sa.Integer(), nullable=False),
        sa.Column("player_recommended_min", sa.Integer(), nullable=False),
        sa.Column("player_max", sa.Integer(), nullable=False),
        sa.Column("player_recommended_max", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_boardgame_name"), "boardgame", ["name"], unique=False)
    op.create_table(
        "play",
        sa.Column("playtime_s", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("won", sa.Boolean(), nullable=False),
        sa.Column("result_str", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "boardgameplaylink",
        sa.Column("boardgame_id", sa.Integer(), nullable=False),
        sa.Column("play_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["boardgame_id"],
            ["boardgame.id"],
        ),
        sa.ForeignKeyConstraint(
            ["play_id"],
            ["play.id"],
        ),
        sa.PrimaryKeyConstraint("boardgame_id", "play_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("boardgameplaylink")
    op.drop_table("play")
    op.drop_index(op.f("ix_boardgame_name"), table_name="boardgame")
    op.drop_table("boardgame")
    # ### end Alembic commands ###
