"""Some fields optional, add weight and ID for board games

Revision ID: feb18c7250b9
Revises: 65d3149e15e1
Create Date: 2024-04-07 18:40:56.885316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'feb18c7250b9'
down_revision: Union[str, None] = '65d3149e15e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boardgame', sa.Column('bgg_id', sa.Integer(), nullable=False))
    op.add_column('boardgame', sa.Column('bgg_weight', sa.Float(), nullable=False))
    op.alter_column('boardgame', 'player_min',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('boardgame', 'player_recommended_min',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('boardgame', 'player_max',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('boardgame', 'player_recommended_max',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boardgame', 'player_recommended_max',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('boardgame', 'player_max',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('boardgame', 'player_recommended_min',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('boardgame', 'player_min',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_column('boardgame', 'bgg_weight')
    op.drop_column('boardgame', 'bgg_id')
    # ### end Alembic commands ###
