
services:
  saboga-api:
    image: saboga-api:latest
    entrypoint: uv run pytest tests --codspeed
    build:
      context: ../
      dockerfile: api-testing/Dockerfile
    container_name: saboga-api
    depends-on:
      saboga-db:
        condition: service_healthy
  saboga-db:
    image: mongo:jammy
    container_name: saboga-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-unit-tests/mongo-init.js:/docker-entrypoint-initdb.d/init-user.js
    options: >-
      --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
      --health-interval=10s
      --health-timeout=5s
      --health-retries=5
