
services:
  saboga-api:
    entrypoint: uv run pytest tests --codspeed
    build:
      context: ../
      dockerfile: api-testing/Dockerfile
    container_name: saboga-api
    depends_on:
      saboga-db:
        condition: service_healthy
  saboga-db:
    image: mongo:jammy
    container_name: saboga-db
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-unit-tests/mongo-init.js:/docker-entrypoint-initdb.d/init-user.js
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
