
services:
  saboga-api-codspeed:
    command: uv run pytest tests/ --codspeed
    build:
      context: ../../
      dockerfile: api-testing/codspeed.Dockerfile
    container_name: saboga-api-codspeed
    networks:
      - ci
    environment:
      - MONGODB_API_USER=test
      - MONGODB_HOST=saboga-db-codspeed
    depends_on:
      saboga-db-codspeed:
        condition: service_healthy

  saboga-db-codspeed:
    image: mongo:jammy
    container_name: saboga-db-codspeed
    volumes:
      - ../../api-testing/mongo-unit-tests/mongo-init.js:/docker-entrypoint-initdb.d/init-user.js
    healthcheck:
      test: mongosh --eval "db.runCommand('ping').ok"
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
      start_interval: 5s
    networks:
      - ci

networks:
  ci:
    internal: true
