name: CodSpeed

on:
  push:
    branches:
      - "main"
  pull_request:
  workflow_dispatch:

jobs:
  benchmarks:
    name: Run benchmarks
    services:
      mongodb:
        image: mongo:8
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: root
        ports:
          - 27017:27017
        volumes:
          - ${{ github.workspace }}/api-testing/mongo-unit-tests/mongo-init.js:/docker-entrypoint-initdb.d/init-user.js
        options: --name mqtt
    env:
      MONGODB_API_USER: test
      MONGODB_HOST: localhost
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Restart
        uses: docker://docker
        with:
          args: docker restart mongodb
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install uv
        run: pip install uv
      - name: Install dependencies
        run: uv venv
      - name: Install dependencies
        run: uv sync --group test
      - name: Wait for MongoDB to be ready
        run: |
          sleep 10  # wait for container healthcheck
      - name: Run benchmarks
        uses: CodSpeedHQ/action@v3
        with:
          token: ${{ secrets.CODSPEED_TOKEN }}
          run: uv run pytest tests/ --codspeed
