name: Integration tests

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: integration-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  test:
    name: Integration test with ${{ matrix.python-version }} on ${{ matrix.os }}
    if: ${{ contains(github.event.head_commit.message, 'needs-integration') || github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install the project
        run: uv sync --group=test
      - uses: extractions/setup-just@v3
      - name: Run test suite
        run: just test --with-slow-integration
      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          parallel: true
          flag-name: python-${{ matrix.python-version }}

  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@v2
        with:
          parallel-finished: true
          carryforward: "python-3.12,python-3.13"
