name: Type checking

on:
  workflow_call:
  pull_request:
  push:
    branches:
      - 'main'

concurrency:
  group: unit-tests-${{ github.ref }}
  cancel-in-progress: true

permissions:
  pull-requests: write

jobs:
  test:
    name: Type check with ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12", "3.13" ]
        os:
          - ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
      - name: Install the project
        run: uv sync --group=test
      - uses: extractions/setup-just@v3
      - name: Run linting
        run: just type
